apiVersion: v1
kind: Pod
metadata:
  name: prom-pod
  labels:
    prom: lbl-prom-pod
spec:
  containers:
    - name: prometheus
      image: prom/prometheus
      volumeMounts:
        - name: config-vol-prom
          mountPath: /etc/prometheus
      ports:
        - containerPort: 9090
  volumes:
    - name: config-vol-prom
      configMap:
        name: prometheus-configmap
        defaultMode: 420