apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    prom: lbl-grafana-svc
spec:
  type: NodePort
  selector:
    prom: lbl-grafana-pod
  ports:
    - port: 3000
      nodePort: 30001