apiVersion: v1
kind: Service
metadata:
  name: contatos-svc
  labels:
    app: lbl-contatos-pod
spec:
  type: NodePort
  selector:
    app: lbl-contatos-pod
  ports:
    - port: 8080
      nodePort: 30000