apiVersion: v1
kind: Pod
metadata:
  name: contatos-pod
  labels:
    app: lbl-contatos-pod
spec:
  volumes:
    - name: vol-contatos
      persistentVolumeClaim:
        claimName: vol-host-pvc
  containers:
    - name: contatos
      image: gladsondevop/contatos:1.0
      volumeMounts:
        - name: vol-contatos
          mountPath: /tmp
      ports:
        - containerPort: 8080