apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-host-pvc
  namespace: default
spec:
  storageClassName: contatvolumeclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi