apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: lbl-db-pod
spec:
  containers:
    - name: db-contatos
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap